name       : pyg3t
version    : 0.3.1
release    : 1
source     :
    - https://launchpad.net/pyg3t/trunk/0.3.1/+download/pyg3t-0.3.1.tar.gz : be8b0953c0c2b2493264dbe7a3359a1e2c97a490cfb3d01699e0360d40ffde35
license    : GPL-3.0
component  : programming.python
summary    : PyG3T, python gettext translation toolkit
description: |
    PyG3T, the Python GetText Translation Toolkit, is a collection of tools for computer assisted translation using GNU gettext.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-dateutil
build      : |
    %python_setup
install    : |
    %python_install
