name       : pyg3t
version    : 0.5.0
release    : 6
source     :
    - https://github.com/pyg3t/pyg3t/archive/0.5.0.tar.gz : 45bcdd4c8ee01491cc66f3e42c632245e9572e7fd1f2ae184fa1839db3e809ba
license    : GPL-3.0
component  : programming.python
summary    : PyG3T, python gettext translation toolkit
description: |
    PyG3T, the Python GetText Translation Toolkit, is a collection of tools for computer assisted translation using GNU gettext.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-dateutil
build      : |
    %python3_setup
install    : |
    %python3_install
